### PR TITLE
Add compatibility with ChartJS v3

### LINKED ISSUE #24: Error: Cannot find module 'rollup/bin/rollup'
Trying to build the project, got an error after running gulp build, what am I doing wrong?

>  node --version
> v14.15.5
>  npm --version
> 7.5.4
>  gulp --version
> CLI version: 2.3.0
> Local version: 4.0.2

Steps to reproduce
> git clone https://github.com/nagix/chartjs-plugin-colorschemes
> cd chartjs-plugin-colorschemes
> npm install
> gulp build

```
isangjae@siin-iui-MacBookPro chartjs-plugin-colorschemes % gulp build
[14:26:46] Using gulpfile /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js
[14:26:46] Starting 'build'...
[14:26:46] 'build' errored after 3.24 ms
[14:26:46] Error: Cannot find module 'rollup/bin/rollup'
Require stack:
- /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js
- /usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js
- /usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
/* global Promise */
- /usr/local/lib/node_modules/gulp/node_modules/gulp-cli/index.js
- /usr/local/lib/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js:24:21
    at new Promise (<anonymous>)
    at run (/Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js:22:9)
    at /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js:40:9
    at build (/Volumes/DK_DEV/project/chartjs-plugin-colorschemes/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (/Volumes/DK_DEV/project/chartjs-plugin-colorschemes/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

### LINKED ISSUE #25: Plugin doesn't work with Chart.js 3.x.x
Please add support for Chartjs 3.x.x or at least mention it in the README since it only says "This plugin requires Chart.js 2.5.0 or later."

Chart.js changed from `Chart.defaults.global` to `Chart.defaults` in the new version. 

image
image

https://www.chartjs.org/docs/master/getting-started/v3-migration/#defaults

### PR DESCRIPTION
**Pull request by MartijnVerkleij**
Hello there! I need to be honest with you, I have not tested this code at all, but this is essentially what came out of my attempts to get the plugin working again. So, it may only bring back rudimentary compatibility.

I have used code from someone else as you can see. ~I need to get in touch to confirm that this is okay.~ I have just received confirmation that this is not an issue.

Fixes #24
Fixes #25

### CODE REVIEW

**Review by sloaxleak — APPROVED** [review]

**Comment by MartijnVerkleij** [comment]
Apologies for the messy commits whilst trying to fix the Travis pipeline :blush:

**Comment by dregad** [comment]
Dear @nagix it would be awesome if you could merge this and publish a new release of this excellent chart.js library ! Thanks in advance.

**Comment by pkunszt** [comment]
yes please @nagix, this would make the plugin usable again with the latest version of chartJS. Thanks!

**Comment by DmytroLitvinov** [comment]
Hi @nagix ,
Thanks a lot for that plugin. It would be nice if we can keep alive that plugin :)

**Comment by mano3m** [comment]
This looks good. Could someone create a minified version of the updated plugin? Thanks!

**Comment by blikblum** [comment]
I just tested and those changes are not enough to get working with chartjs v3.

I created a working branch at https://github.com/blikblum/chartjs-plugin-colorschemes/tree/v3

Time allowing i will do a proper PR

**Comment by nagix** [comment]
@MartijnVerkleij Thank you for your contribution! This looks good to me.

**Pull request merged**
